package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import neu.scweb.util.Counter;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(2);
    _jspx_dependants.add("/jsp/count.jsp");
    _jspx_dependants.add("/jsp/date.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC “-//W3C//DTD XHTML 1.0 Transitional//EN” “http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd”>\r\n");
      out.write("\r\n");

	String basepath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"Keywords\" content=\"东北大学软件学院,东北大学国家示范性软件学,东北大学软件工程,东北大学信息安全,东北大学数字媒体技术\">\r\n");
      out.write("<meta name=\"description\" content=\"东北大学国家示范性软件学院官方网站，软件学院概况、师资队伍、教学情况、日常管理等信息\">\r\n");
      out.write("<link href=\"");
      out.print(basepath);
      out.write("/icons/favicon.ico\"  rel=\"shortcut icon\" />\r\n");
      out.write("<link href=\"");
      out.print(basepath);
      out.write("/css/header.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.print(basepath);
      out.write("/css/picturenews.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.print(basepath);
      out.write("/css/jquery-ui-1.8.14.custom.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.print(basepath);
      out.write("/css/index.css\" rel=\"stylesheet\"  type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(basepath);
      out.write("/css/banner.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.print(basepath);
      out.write("/css/superfish.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("div#index-manage{\r\n");
      out.write("\twidth:1022px;\r\n");
      out.write("\tborder:1px solid #A8A8A8;\r\n");
      out.write("\theight:0px;\r\n");
      out.write("\tbackground-image:url('images/index-manage-bg.jpg');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#index-manage span{\r\n");
      out.write("\tfont-family:\"黑体\";\r\n");
      out.write("\tmargin-left:40px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tline-height:34px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("p#swc-ch{\r\n");
      out.write("\tfont-family:\"黑体\";\r\n");
      out.write("\tfront-size:14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p#header-title{\r\n");
      out.write("\tfront-size:20px;\r\n");
      out.write("\tfont-family:\"黑体\";\r\n");
      out.write("\t\r\n");
      out.write("\tmargin-left:40px;\r\n");
      out.write("\tcolor: #4A8B9F;\r\n");
      out.write("\tline-height:34px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<title>东北大学国家示范性软件学院</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"index-container\">\r\n");
      out.write("\t<!-- container begin -->\t \r\n");
      out.write("\t\t<div id=\"header-ad\"></div>\t\r\n");
      out.write("\t\t<div id=\"header-container\">\r\n");
      out.write("\t\t<!-- header-container begin -->\r\n");
      out.write("\t\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t\t<div id=\"swc\">\r\n");
      out.write("\t\t\t\t<!-- swc begin -->\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(basepath);
      out.write("/images/header-title.jpg\"> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- swc end -->\r\n");
      out.write("\t\t\t\t<div id=\"search\">\r\n");
      out.write("\t\t\t\t<!-- search begin -->\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"searchbox\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- search end -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- header end -->\r\n");
      out.write("\t\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<!-- menu beign -->\t\t   \t\t   \t\t\t\t   \t\t   \t\t\r\n");
      out.write("\t\t\t\t<ul class=\"sf-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"current\"><a href=\"index.jsp\" class=\"parent\"><span>学院首页</span></a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a class=\"parent\"><span>学院概况</span></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"guideLi2\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1008\"><span>学院简介</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/org.jsp?orgId=1\" target=\"_blank\"><span>理事会</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/org.jsp?orgId=2\" target=\"_blank\"><span>学院领导</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1002\"><span>大事记</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"parent\"><span>机构设置</span></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"guideLi3\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/org.jsp?orgId=3\"><span>学院办公室</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/org.jsp?orgId=4\"><span>教学科研办公室</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/org.jsp?orgId=5\"><span>学生工作办公室</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/department.jsp?orgId=6\"><span>软件工程研究所</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/department.jsp?orgId=7\"><span>信息安全研究所</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/department.jsp?orgId=8\"><span>数字媒体技术研究所</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/department.jsp?orgId=9\"><span>外语教学部</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/department.jsp?orgId=10\"><span>实验中心</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li><li><a class=\"parent\"><span>师资队伍</span></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"guideLi4\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1009\"><span>队伍概况</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/teacherList.jsp\"><span>教师队伍</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"parent\"><span>党政工作</span></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"guideLi5\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10002&amp;page=1\"><span>党建工作</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10003&amp;page=1\"><span>人事行政</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"parent\"><span>人才培养</span></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"guideLi6\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"parent\"><span>本科生教学</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"guideLi28\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10016&amp;page=1\"><span>教学管理</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10017&amp;page=1\"><span>教学改革</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"parent\"><span>研究生教学</span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"guideLi29\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10020&amp;page=1\"><span>教学管理</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10022&amp;page=1\"><span>教学点管理</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"parent\"><span>招生工作</span></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"guideLi7\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10012&amp;page=1\"><span>招生信息</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"parent\"><span>本科生专业</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"guideLi42\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1022\"><span>软件工程</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1023\"><span>信息安全</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1024\"><span>数字媒体技术</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"parent\"><span>研究生专业</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"guideLi43\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1025\"><span>软件工程（学术型）</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1026\"><span>软件工程（应用型）</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1027\"><span>软件工程（单证）</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/yjsds.jsp\"><span>研究生导师</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"parent\"><span>学生工作</span></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"guideLi8\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10007&amp;page=1\"><span>日常管理</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10008&amp;page=1\"><span>学生活动</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10009&amp;page=1\"><span>就业信息</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"parent\"><span>学生科创</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"guideLi41\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10010&amp;page=1\"><span>科技竞赛</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10011&amp;page=1\"><span>创新项目</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10029&amp;page=1\"><span>学生社团</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"parent\"><span>学科科研</span></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"guideLi9\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10004&amp;page=1\"><span>学科建设</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10005&amp;page=1\"><span>科学研究</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10006&amp;page=1\"><span>学术活动</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/page.jsp?pageId=1005\"><span>研究室</span></a></li><li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"jsp/page.jsp?pageId=1006\"><span>联合实验室</span></a></li><li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"jsp/page.jsp?pageId=1007\"><span>工程中心</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"parent\"><span>合作交流</span></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"guideLi10\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10013&amp;page=1\"><span>校企合作</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"jsp/newsList.jsp?id=10014&amp;page=1\"><span>国际交流</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- menu end -->\r\n");
      out.write("\t\t\t<div id=\"header-flash\">\r\n");
      out.write("\t\t\t\t<div id=\"header-flash-place\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"header-line\"></div> \r\n");
      out.write("\t\t\t<div id=\"header-login\">\r\n");
      out.write("\t\t\t<form name=\"loginform\" action=\"userAction!login\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table width=\"980px\">\r\n");
      out.write("\t\t\t\t\t<tr>\t\t\r\n");
      out.write("\t\t\t\t\t\t<td width=\"35px\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"60px\"><span class=\"header-login\">用户名：</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"110px\"><input type=\"text\" name=\"userName\" style=\"width:90px;height:20px;\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"45px\"><span class=\"header-login\">密码：</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100px\"><input type=\"password\" name=\"userPsw\" style=\"width:90px;height:20px;\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"55px\"><input type=\"image\" border=\"0\" name=\"submit\" src=\"");
      out.print(basepath);
      out.write("/images/header-login-button-submit.png\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"55px\"><input type=\"image\" border=\"0\" name=\"reset\" src=\"");
      out.print(basepath);
      out.write("/images/header-login-button-cancle.png\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td width=\"150px\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><span class=\"header-login-info\">总访问量：");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Counter cb=new Counter();String counter=cb.getCounter();
      out.write('\r');
      out.write('\n');
      out.print(counter );
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</span>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t<td><span class=\"header-login-info\"> ");
      out.write("\r\n");
      out.write("<script language=\"javascript\"> \r\n");
      out.write("\tfunction PageDate(){   \r\n");
      out.write("\t\tcurrentDate = new Date();  \r\n");
      out.write("\t\twith(currentDate){   \r\n");
      out.write("\t\t\tday=getDay();\r\n");
      out.write("\t\t\tmonth=getMonth()+1;\r\n");
      out.write("\t\t\tthis.document.write(getFullYear()+'年'+month+'月'+getDate()+'日')   \r\n");
      out.write("\t\t}   \r\n");
      out.write("\t\tif(day==1){document.write(' 星期一');}\r\n");
      out.write("\t\tif(day==2){document.write(' 星期二');}\r\n");
      out.write("\t\tif(day==3){document.write(' 星期三');}\r\n");
      out.write("\t\tif(day==4){document.write(' 星期四');}\r\n");
      out.write("\t\tif(day==5){document.write(' 星期五');}\r\n");
      out.write("\t\tif(day==6){document.write(' 星期六');}\r\n");
      out.write("\t\tif(day==0){document.write(' 星期日');} \r\n");
      out.write("\t}\r\n");
      out.write("\tPageDate();\r\n");
      out.write("</script>");
      out.write("</span>&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"header-line2\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<tbody><tr>\r\n");
      out.write("\t\t\t\t<th rowspan=\"2\" width=\"40px\"></th>\r\n");
      out.write("\t\t\t\t<th rowspan=\"2\" valign=\"top\">\r\n");
      out.write("\t\t\t\t  \t<div id=\"index-left\" class=\"connectedSortable\">\r\n");
      out.write("\t\t\t\t\t  \t<div id=\"news10001\" class=\"index-side\">\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"index-side-header\"><span class=\"part-name\">最新公告</span></div>\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"index-side-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"index-side-content\" id=\"10001\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t<div class=\"index-news-blank\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t<marquee id=\"announcement\" onmouseover=\"announcement.stop()\" onmouseout=\"announcement.start()\" scrollamount=\"1\" scrolldelay=\"1\" direction=\"up\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t</marquee>\r\n");
      out.write("\t\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"index-side-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/newsList.jsp?id=10001&amp;page=1\">更多</a></span></div>\r\n");
      out.write("\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t  \t<div id=\"news10031\" class=\"index-side\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-side-header\"><span class=\"part-name\">学院动态</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-side-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-side-content\" id=\"10031\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"index-news-blank\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-side-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/newsList.jsp?id=10031&amp;page=1\">更多</a></span></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t  \t\t<div id=\"news10028\" class=\"index-side\">\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"index-side-header\"><span class=\"part-name\">学生科创</span></div>\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"index-side-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"index-side-content\" id=\"10028\">\r\n");
      out.write("\t\t\t\t\t\t  \t\t<div class=\"index-news-blank\"></div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-side-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/newsList.jsp?id=10028&amp;page=1\">更多</a></span></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t \t</th>\r\n");
      out.write("\t\t\t \t<td height=\"216px\" valign=\"top\">\r\n");
      out.write("\t\t\t \t\t<div id=\"picturenews\">\r\n");
      out.write("\t\t\t \t\t<!-- picturenews begin -->\r\n");
      out.write("\t\t\t \t\t\t<div id=\"picturenews-header\"><span class=\"part-name\"><strong>图片新闻</strong></span></div>\r\n");
      out.write("\t\t\t \t\t\t<div id=\"picturenews-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"picturenews-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"picturenews_piclist\" style=\"left:0; top:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul id=\"picturenews_ul_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"picturenews_opdiv\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"picturenews_btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"picturenews_ul_right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"picturenews_tx\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul id=\"picturenews_ul_tx\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
     
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t \t\t</div>\r\n");
      out.write("\t\t\t \t\t<!-- picturenews end -->\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t \t<th rowspan=\"2\" valign=\"top\">\r\n");
      out.write("\t\t \t\t\t<div id=\"index-right\" class=\"connectedSortable\">\r\n");
      out.write("\t\t\t \t\t\t<div id=\"kuaisutongdao\" class=\"index-right-side\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"index-right-header\"><span class=\"part-name\">快速通道</span></div>\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"index-right-line\"></div>\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"index-right-body\">\r\n");
      out.write("\t\t\t\t \t\t\t\t<div class=\"index-news-blank\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"ksLink\"  href=\"http://sc.neu.edu.cn/jsp/newsContent.jsp?sectionId=10012&newsId=470\" target=\"_blank\">软件工程硕士自主招生</a>\r\n");
      out.write("\t\t\t\t\t \t\t\t<a class=\"ksLink\"  href=\"http://bb.neu.edu.cn/\" target=\"_blank\">Blackboard平台</a>\r\n");
      out.write("\t\t\t\t\t \t\t\t<a class=\"ksLink\"  href=\"http://kjc.neu.edu.cn/business/login.jsp\" target=\"_blank\">科研管理平台</a>\r\n");
      out.write("\t\t\t\t\t \t\t\t<a class=\"ksLink\"  href=\"http://202.118.31.197/ACTIONQUERYTEACHERSCHEDULEBYPUBLIC.APPPROCESS\" target=\"_blank\">教师课表查询</a>\r\n");
      out.write("\t\t\t\t\t \t\t\t<a class=\"ksLink\"  href=\"http://202.118.31.197:8000/xk_login.jsp\" target=\"_blank\">学生选课系统</a>\r\n");
      out.write("\t\t\t\t\t \t\t\t<a class=\"ksLink\"  href=\"http://202.118.31.197/ACTIONQUERYSTUDENTSCHEDULEBYSELF.APPPROCESS\" target=\"_blank\">学生课表查询</a>\r\n");
      out.write("\t\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"index-right-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/kuaisu.jsp\">更多</a></span></div>\r\n");
      out.write("\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t \t\t\t<div id=\"news10025\" class=\"index-right-side\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"index-right-header\"><span class=\"part-name\">学生工作</span></div>\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"index-right-line\"></div>\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"index-right-body\" id=\"10025\">\r\n");
      out.write("\t\t\t\t \t\t\t\t<div class=\"index-news-blank\"></div>\r\n");
      out.write("\t\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"index-right-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/newsList.jsp?id=10025&amp;page=1\">更多</a></span></div>\r\n");
      out.write("\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t \t\t\t<div id=\"news10030\" class=\"index-right-side\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-right-header\"><span class=\"part-name\">招生就业</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-right-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-right-body\" id=\"10030\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"index-news-blank\"></div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-right-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/newsList.jsp?id=10030&amp;page=1\">更多</a></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t \t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t  <td valign=\"top\">\r\n");
      out.write("\t\t\t\t<div id=\"index-center\">\r\n");
      out.write("\t\t\t\t<!-- index center begin -->\r\n");
      out.write("\t\t\t\t\t<div id=\"index-center-left\" class=\"connectedSortable\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"news10026\" class=\"index-center-news\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-header\"><span class=\"part-name2\"><strong>本科生教学</strong></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-content\" id=\"10026\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-news-blank\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--[if IE 6]> <br/><![endif]-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/newsList.jsp?id=10026&amp;page=1\">更多</a></span></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"news10014\" class=\"index-center-news\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-header\"><span class=\"part-name2\"><strong>国际交流</strong></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-content\" id=\"10014\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-news-blank\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--[if IE 6]> <br/><![endif]-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/newsList.jsp?id=10014&amp;page=1\">更多</a></span></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"index-center-right\" class=\"connectedSortable\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"news10027\" class=\"index-center-news\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-header\"><span class=\"part-name2\"><strong>研究生教学</strong></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-content\" id=\"10027\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-news-blank\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--[if IE 6]> <br/><![endif]-->\r\n");
      out.write("\t\t\t\t\t\t\t </div><div class=\"index-center-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/newsList.jsp?id=10027&amp;page=1\">更多</a></span></div>\r\n");
      out.write("\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"news10013\" class=\"index-center-news\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-header\"><span class=\"part-name2\"><strong>校企合作</strong></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-content\" id=\"10013\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-news-blank\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--[if IE 6]> <br/><![endif]--></div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-center-bottom\"><img src=\"images/index-arrow.png\"><span class=\"news-more\"><a href=\"jsp/newsList.jsp?id=10013&amp;page=1\">更多</a></span></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"slidePic\" style=\"overflow:hidden;height:89px;width:520px;color:#ff0000;margin-left:10px;\">\r\n");
      out.write("\t\t\t\t\t\t<table align=\"left\" border=\"0\" cellpadding=\"0\"><tbody><tr><td id=\"slideRound1\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t  <tbody><tr>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10000.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10001.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10002.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10003.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10004.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10005.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10006.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t  </tbody></table>\r\n");
      out.write("\t\t\t\t\t\t </td><td id=\"slideRound2\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t  <tbody><tr>\r\n");
      out.write("\t\t\t\t\t\t   <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10000.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10001.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10002.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10003.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10004.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10005.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    <td><div class=\"roundPic\"><a href=\"jsp/pictures.jsp\"><img src=\"roundPic/10006.jpg\" height=\"84px\" width=\"152px\"></a></div></td>\r\n");
      out.write("\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t  </tbody></table>\r\n");
      out.write("\t\t\t\t\t\t </td></tr></tbody></table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t  <script>\r\n");
      out.write("\t\t\t\t\t\t  var speed=50//速度数值越大速度越慢\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  document.getElementById(\"slideRound2\").innerHTML=document.getElementById(\"slideRound1\").innerHTML\r\n");
      out.write("\t\t\t\t\t\t  function Marquee(){\r\n");
      out.write("\t\t\t\t\t\t  if(document.getElementById(\"slideRound2\").offsetWidth-document.getElementById(\"slidePic\").scrollLeft<=0)\r\n");
      out.write("\t\t\t\t\t\t  document.getElementById(\"slidePic\").scrollLeft-=document.getElementById(\"slideRound1\").offsetWidth\r\n");
      out.write("\t\t\t\t\t\t  else{\r\n");
      out.write("\t\t\t\t\t\t  document.getElementById(\"slidePic\").scrollLeft++\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  var MyMar=setInterval(Marquee,speed)\r\n");
      out.write("\t\t\t\t\t\t  document.getElementById(\"slidePic\").onmouseover=function() {clearInterval(MyMar)}\r\n");
      out.write("\t\t\t\t\t\t  document.getElementById(\"slidePic\").onmouseout=function() {MyMar=setInterval(Marquee,speed)}\r\n");
      out.write("\t\t\t\t\t\t  </script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- index center end -->\r\n");
      out.write("\t\t\t  </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody></table>\r\n");
      out.write("\t\t<div id=\"banner\">\r\n");
      out.write("\t\t<!-- banner begin -->\r\n");
      out.write("\t\t\t<div id=\"banner-line\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"banner-text\">\r\n");
      out.write("\t\t\t\t<table height=\"25px\" width=\"500px\">\r\n");
      out.write("\t\t\t\t\t<tbody><tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"border-right:1px solid #a0a0a0\" align=\"center\"><p class=\"banner2\"><a target=\"_blank\" href=\"introduction/contactus.jsp\">联系我们</a></p></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"border-right:1px solid #a0a0a0\" align=\"center\"><p class=\"banner2\"><a target=\"_blank\" href=\"introduction/codeInfo.jsp\">技术支持</a></p></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"border-right:1px solid #a0a0a0\" align=\"center\"><p class=\"banner2\"><a target=\"_blank\" href=\"jsp/page.jsp?pageId=1010\">友情链接</a></p></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"border-right:1px solid #a0a0a0\" align=\"center\"><p class=\"banner2\"><a target=\"_blank\" href=\"jsp/newsList.jsp?id=10015&amp;page=1\">诚聘英才</a></p></td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><p class=\"banner2\"><a target=\"_blank\" href=\"jsp/downloadList.jsp?page=1&amp;sec=all\">资源下载</a></p></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody></table>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%';\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<p id=\"banner1\">© Copyright 2011 Software College Northeastern University. 东北大学软件学院. All rights reserved.</p>\r\n");
      out.write("\t\t\t\t\t<p id=\"banner1\">地址：辽宁省沈阳市和平区文化路3号巷11号      邮编：110819 </p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t<!-- banner end -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basepath);
      out.write("/js/jquery.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basepath);
      out.write("/js/jquery.easing-1.3.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basepath);
      out.write("/js/picnews.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basepath);
      out.write("/js/hoverIntent.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basepath);
      out.write("/js/superfish.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basepath);
      out.write("/js/swfobject.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basepath);
      out.write("/js/index.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
